services:
  mock-mcp:
    image: openresty/openresty@sha256:dd00479e7a68b8ce1b18bcb519d74cbf2e62eb539026f3c680f2f391aeb545bb
    container_name: mock-mcp
    ports:
      - "8088:8088"
      - "8081:8081"
    volumes:
      - ./default.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ../nginx-logs:/data/nginx-logs
    networks:
      - mock_net

networks:
  mock_net:
