[FILTER]
    Name                  parser
    Match                 provost.error
    Key_Name              message
    Parser                provost-error-audit-json
    Reserve_Data          On
    Preserve_Key          On

[FILTER]
    Name                  parser
    Match                 provost.error
    Key_Name              audit_json
    Parser                json
    Reserve_Data          On
    Preserve_Key          Off
