[FILTER]
    Name                  rewrite_tag
    Match                 provost.raw
    Rule                  ident ^provost_.*_access$ provost.access true
    Rule                  ident ^provost_.*_error$ provost.error true
