[FILTER]
    Name                  parser
    Match                 provost.raw
    Key_Name              message
    Parser                json
    Reserve_Data          On
    Preserve_Key          On
