[FILTER]
    Name          rewrite_tag
    Match         provost.access
    Rule          $time_local ^\d{2}/[a-zA-Z]{3}/\d{4}:(\d{2}):.*$ $TAG.$1 false
    Emitter_Name  re_emitted_access

[FILTER]
    Name          rewrite_tag
    Match         provost.error
    Rule          $time_local ^\d{2}/[a-zA-Z]{3}/\d{4}:(\d{2}):.*$ $TAG.$1 false
    Emitter_Name  re_emitted_error
