[OUTPUT]
    Name                  s3
    Match                 provost.access.*
    bucket                ${S3_BUCKET}
    region                ${AWS_REGION}
    total_file_size       1M
    upload_timeout        60s
    use_put_object        On
    send_content_md5      On
    json_date_key         false
    s3_key_format         /agent-provost/logs/access/%Y/%m/%d/$TAG[2]/$UUID.json
    s3_key_format_tag_delimiters .
    store_dir             /var/log/fluent-bit/storage/s3

[OUTPUT]
    Name                  s3
    Match                 provost.error.*
    bucket                ${S3_BUCKET}
    region                ${AWS_REGION}
    total_file_size       1M
    upload_timeout        60s
    use_put_object        On
    send_content_md5      On
    json_date_key         false
    s3_key_format         /agent-provost/logs/error/%Y/%m/%d/$TAG[2]/$UUID.json
    s3_key_format_tag_delimiters .
    store_dir             /var/log/fluent-bit/storage/s3
