[OUTPUT]
    Name                  s3
    Match                 provost.*
    bucket                ${S3_BUCKET}
    region                ${AWS_REGION}
    total_file_size       1M
    upload_timeout        1m
    use_put_object        On
    send_content_md5      On
    s3_key_format         /agent-provost/logs/%Y/%m/%d/%H/$UUID.json
    store_dir             /var/log/fluent-bit/storage/s3
