@SET CI_TESTING=${CI_TESTING:-false}

@IF EQ CI_TESTING true
[OUTPUT]
    Name    file
    Match   provost.access.*
    Path    /var/log/fluent-bit/storage
    Format  plain

[OUTPUT]
    Name    file
    Match   provost.error.*
    Path    /var/log/fluent-bit/storage
    Format  plain
@ENDIF
