[OUTPUT]
    Name                  file
    Match                 provost.access.*
    Path                  /var/log/fluent-bit/storage/final
    File                  access.jsonl
    Format                json_lines

[OUTPUT]
    Name                  file
    Match                 provost.error.*
    Path                  /var/log/fluent-bit/storage/final
    File                  error.jsonl
    Format                json_lines